### ISSUE TITLE
usync blank site front page showed up in error

### ISSUE THREAD

**Issue by SATC-Ben** [Jumoo/jumoo-docs#30]
Using usync: 11.2.0 umbraco: 11.4.0
The following page was displayed on our high-traffic site over the weekend. Once the site was restarted, the site went back to normal.
This is most likely a failure with Umbraco that might cause this but I'd really like to understand, how I could prevent this page from showing up on issues. Or even being able to replace it with something more brand-friendly.
Are you able to give me any insight as to what the factors are that might have led to this page showing up? 
<img width="282" alt="image" src="https://github.com/Jumoo/jumoo-docs/assets/107968597/42a4cf53-599f-4f57-8f4d-439e36df8394">

**Comment by KevinJump** [comment]
Hi,

To show this screen uSync has only changed a 'NoNodes' setting (see https://github.com/KevinJump/uSync/blob/b2ffa7e75841433a6a3185474bc5af0a6fc6e1c0/uSync.BackOffice/Boot/uSyncBootExtension.cs#L31-L38 ) 

Control over whether or not this page actually shows is controlled by Umbraco. 

So if Umbraco thinks it has no content it will render this page. 

```cs
// Check if there is no existing content and return the no content controller
if (!umbracoContext.Content?.HasContent() ?? false)
{
    return new RouteValueDictionary
    {
        [ControllerToken] = ControllerExtensions.GetControllerName<RenderNoContentController>(),
        [ActionToken] = nameof(RenderNoContentController.Index),
    };
}
```
(https://github.com/umbraco/Umbraco-CMS/blob/b923c3252537468a7ecad2d394f37c0dbc7387ae/src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs#L189-L197)

Looking into that the `HasContent` method is returns true if there is any content in the published cache, so it would appear for some reason that your site temporally thought it had no published content ? 

I am not sure how this might occur, but i think either the content is being cleared somewhere ? or somehow loading that content failed ? I suspect restarting the site will have reloaded the content cache.

**Comment by SATC-Ben** [comment]
Brilliant, thanks a lot. 

The issue occurred in Azure so I would say the cache was inaccessible temporarily from a SaaS issue or instance upgrade but otherwise functioned correctly. 

I'll take it up with Umbraco to see if there is a way this can be detected and a cache rebuild triggered.
