### ISSUE TITLE
[QUERY] uSync.Publisher Config docs query

### ISSUE THREAD

**Issue by NikRimington** [Jumoo/jumoo-docs#43]
Hi  @KevinJump 

I was reading the docs for [uSync.Publisher Config](https://github.com/Jumoo/jumoo-docs/blob/master/versioned_docs/version-10.x/02.complete/03.publisher/01.config.md) and it states `for uSync 9 and 10` is that the case for all versions up from v9, so v13 as well? If not, where is v13 config stored as I couldn't spot that in the docs?

If it is the case, are you happy for me to update the docs to read `for uSync 9+` ?

Thanks

Nik

**Comment by KevinJump** [comment]
Just for completeness (and so we remember to update the docs).

---

The sending server will look in the appsettings for `uSync:Publisher:Servers:{serverAlias}:AppId` and `"uSync:Publisher:Servers:{serverAlias}:AppKey` and if they are not there it uses the default values (so the 'normal' ones. 

e.g 

```json
"Publisher": {
  "Servers": {
    "live": {
      "AppId": "649a7ef0-9b31-4236-8c0a-5449fc767786",
      "AppKey": "CKMpw1imuQvPfq8rPO4ipw9mcdahFATdimD4UL6MOFA=","
    }
  }
```

The target server will as "normal" need these keys in publisher/settings

e.g.

```json
    "Publisher": {
      "Settings": {
        "IncomingEnabled": true,
        "AppId": "649a7ef0-9b31-4236-8c0a-5449fc767786",
        "AppKey": "CKMpw1imuQvPfq8rPO4ipw9mcdahFATdimD4UL6MOFA=",
```
